config/routes.rb
Rails.application.routes.draw do

  get 'other_users/new', as: 'other_user'
  post 'other_users/new', to: 'other_users#create'

  resources :users

end

app/models/active_model_user.rb
class ActiveModelUser
  include ActiveModel::Model

  attr_accessor :name, :name_kana, :tel, :mail, :birthday, :question
  define_model_callbacks :save
  before_save { self.valid? }

  validate :add_error

  def add_error
    errors[:base] << "氏名が入力されていません。" if name.empty?
    errors[:base] << "氏名(カナ)が入力されていません。" if name_kana.empty?
    errors[:base] << "電話番号が入力されていません。" if tel.empty?
    errors[:base] << "メールアドレスが入力されていません。" if mail.empty?
    errors[:base] << "生年月日が入力されていません。" if birthday.empty?
    # errors.add(:name, "氏名が入力されていません。") if name.empty?
    # errors.add(:name_kana, "氏名(カナ)が入力されていません。") if name_kana.empty?
    # errors.add(:tel, "電話番号が入力されていません。") if tel.empty?
    # errors.add(:mail, "メールアドレスが入力されていません。") if mail.empty?
    # errors.add(:birthday, "生年月日が入力されていません。") if birthday.empty?
  end

  def save
    run_callbacks :save do
      # raise
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/other_user.rb
class OtherUser
  include ActiveModel::Model

  attr_accessor :name, :name_kana, :tel, :mail, :birthday, :question
  # コーリバックさせたいアクションを指定
  define_model_callbacks :save
  before_save {
    # raise
    self.valid? }

  validate :add_error

  def question(param = {})
    ['a', 'b', 'c']
  end

  def add_error
    errors[:base] << "氏名が入力されていません。" if name.empty?
    errors[:base] << "氏名(カナ)が入力されていません。" if name_kana.empty?
    errors[:base] << "電話番号が入力されていません。" if tel.empty?
    errors[:base] << "メールアドレスが入力されていません。" if mail.empty?
    errors[:base] << "生年月日が入力されていません。" if birthday.empty?
    # errors.add(:name, "氏名が入力されていません。") if name.empty?
    # errors.add(:name_kana, "氏名(カナ)が入力されていません。") if name_kana.empty?
    # errors.add(:tel, "電話番号が入力されていません。") if tel.empty?
    # errors.add(:mail, "メールアドレスが入力されていません。") if mail.empty?
    # errors.add(:birthday, "生年月日が入力されていません。") if birthday.empty?
  end

  def save
    # コールバック発火
    run_callbacks :save do
      # raise
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :name_kana, presence: true
  validates :tel, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :mail, presence: true, length: { maximum: 255 },
                   format: { with: VALID_EMAIL_REGEX },
                   uniqueness: { case_sensitive: false }
  validates :birthday, presence: true
  validates :question,  length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/other_users_controller.rb
class OtherUsersController < ApplicationController

  def new
    @other_user = OtherUser.new(name: nil, name_kana: nil, tel: nil, mail: nil, birthday: nil, question: ['a', 'b', 'c'])
  end

  def create
    @other_user = OtherUser.new(other_user_params)
    # raise
    if @other_user.save
      flash[:success] = "Other_User created!!!"
      redirect_to @other_user, notice: 'Other User was successfully created.'
    else
      render :new
    end
  end

  private
    # マスアサインメント対策 Strong Parameters
    def other_user_params
      params.require(:other_user).permit(:name, :name_kana, :tel, :mail, :birthday, :question)
    end

    # strong parameters
    def submit_params
      permit_attrs = []
      @other_user.all.each do |item|
        permit_attrs.push("#{item.id}".to_sym)
      end
      params.require(:other_user).permit(permit_attrs)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "User created!!!"
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :name_kana, :tel, :mail, :birthday, :question)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/other_users_helper.rb
module OtherUsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleForm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/other_users/_form.html.erb
<%= form_for(@other_user, url: other_user_path) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :name_kana %>
    <%= form.text_field :name_kana, id: :user_name_kana %>
  </div>

  <div class="field">
    <%= form.label :tel %>
    <%= form.text_field :tel, id: :user_tel %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail, id: :user_mail %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.text_field :birthday, id: :user_birthday %>
  </div>

  <div class="field">
    <%= form.label :question %>
    <!-- <%= @other_user.question.each_with_index do |val,i| %>
      <div>
        <%= form.label :val %>
        <%= text_area :val, size: "80x10" %>
      </div>
    <% end %> -->
    <%= form.text_area :question, id: :user_question, size: "80x10" %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/other_users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @other_user %>

<%= link_to 'Back', users_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :name_kana %>
    <%= form.text_field :name_kana, id: :user_name_kana %>
  </div>

  <div class="field">
    <%= form.label :tel %>
    <%= form.text_field :tel, id: :user_tel %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail, id: :user_mail %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.text_field :birthday, id: :user_birthday %>
  </div>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question, id: :user_question %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form0.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :name_kana %>
    <%= form.text_field :name_kana, id: :user_name_kana %>
  </div>

  <div class="field">
    <%= form.label :tel %>
    <%= form.text_field :tel, id: :user_tel %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail, id: :user_mail %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.text_field :birthday, id: :user_birthday %>
  </div>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question, id: :user_question %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Name kana</th>
      <th>Tel</th>
      <th>Mail</th>
      <th>Birthday</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.name_kana %></td>
        <td><%= user.tel %></td>
        <td><%= user.mail %></td>
        <td><%= user.birthday %></td>
        <td><%= user.question %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %> |
<%= link_to 'New Active Model User', other_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/new_active_model.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Name kana:</strong>
  <%= @user.name_kana %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @user.tel %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @user.mail %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Question:</strong>
  <%= @user.question %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>